/**: # wildcard for the node name
  ros__parameters:
    p_gain:
      x: 3.0  # 4.0
      y: 3.0
      z: 3.0
    d_gain:
      x: 1.8  # 2.0  
      y: 1.8
      z: 1.8
    beta: 0.2 # Filter Value
    scale_Kp_by: 0.6
    scale_Kd_by: 0.6